name: bloc_presentation
description: >
  Extends blocs with an additional stream which can serve as a way of indicating
  single-time events (so-called "presentation events").
version: 1.1.0
homepage: https://github.com/leancodepl/bloc_presentation/tree/master/packages/bloc_presentation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: '^15.0.0'
  mocktail: ^1.0.0
