name: bloc_presentation
description: >
  Extends blocs with an additional stream which can serve as a way of indicating
  single-time events (so-called "presentation events").
version: 0.2.1+2
homepage: https://github.com/leancodepl/bloc_presentation/tree/master/packages/bloc_presentation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.20.0
  nested: ^1.0.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: '>=5.0.0'
  mocktail: ^1.0.0
