name: bloc_presentation_test test

on:
  push:
    branches: [master]
    tags-ignore: ['bloc_presentation_test-v*']
    paths:
      - 'packages/bloc_presentation_test/**'
      - .github/workflows/bloc_presentation_test-test.yml
  pull_request:
    branches: [master]
    paths:
      - 'packages/bloc_presentation_test/**'
      - .github/workflows/bloc_presentation_test-test.yml

jobs:
  test:
    name: Flutter ${{ matrix.flutter.version }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flutter:
          - version: '3.10.x'
          - version: '3.13.x'
          - version: '3.27.x'
            analyze: true

    defaults:
      run:
        working-directory: packages/bloc_presentation_test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter.version }}
          cache: true

      - name: Download pub dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed --output none .

      - name: Run analyzer
        if: ${{ matrix.flutter.analyze }}
        run: flutter analyze --fatal-warnings --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Dry run pub publish
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
        with:
          dry-run: true
          path: packages/bloc_presentation_test
