name: prepare

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    name: Flutter ${{ matrix.version }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['3.3.x', '3.7.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Download pub dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed --output none .

      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Dry run pub publish
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
        with:
          dry-run: true
