name: publish

on:
  push:
    tags: ['v*']

jobs:
  main:
    name: Publish to pub.dev

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # setup-dart is required to be able to use GitHub Automated Publishing
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'
          cache: true

      - name: Publish and release
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
